//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
//using System.Windows.Forms;
namespace BDProject.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        string strLogIn = "";
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        //[global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLNCLI11;Data Source=DESKTOP-8HJI3PV\\SQLEXPRESS;Integrated Security=SSP" +
        //    "I;Initial Catalog=FKR")]
        public string ConnectionString {
            get {
                if(this.strLogIn == ""){
                    LoginForm frm = new LoginForm();
                    if(frm.ShowDialog() == System.Windows.Forms.DialogResult.OK)
                    {
                        this.strLogIn="User ID = "+ frm.tbName.Text.Trim() + "; Password = "+frm.tbPwd.Text.Trim() + ";";
                    }else{
                        Environment.Exit(0);
                    }
                }
                
                string S = "Provider=SQLOLEDB.1;Persist Security Info=True;" +
                    "Initial Catalog=FKR;Data Source=DESKTOP-8HJI3PV\\SQLEXPRESS;"+ this.strLogIn;
                return ((string)(S));
                //return ((string)(this["ConnectionString"]));
            }
        }
    }
}
